// AUTH
export const REQUEST_PHONE = 'REQUEST_PHONE'
export const REQUEST_LOCATION = 'REQUEST_LOCATION'
export const REQUEST_LEGAL_NAME = 'REQUEST_LEGAL_NAME'
export const REQUEST_SHOP_NAME = 'REQUEST_SHOP_NAME'
export const REQUEST_REGION = 'REQUEST_REGION'
export const REQUEST_LOCATION_TEXT = 'REQUEST_LOCATION_TEXT'


export const START = 'START';
export const CHOOSE_POSITION = 'CHOOSE_POSITION';
export const CHOOSE_SIZE = 'CHOOSE_SIZE';
export const CHOOSE_QUANTITY = 'CHOOSE_QUANTITY';
export const CHOOSE_TASTE = 'CHOOSE_TASTE';
export const FETCH_MY_ORDERS = 'FETCH_MY_ORDERS';
export const CHOOSE_SETTING = 'SHOOSE_SETTING';

export const BASKET = 'BASKET';


export const CHECKOUT = 'CHECKOUT';
export const PAY_BY_CASH = 'PAY_BY_CASH';
export const PAY_BY_TRANSFER = 'PAY_BY_TRANSFER';


// ORDERS
export const ORDERS_LIST = 'ORDERS_LIST'



